Add Stars badges for GitHub repositories
lirantal/awesome-opensource-israel pull request #115
Opened 2023-02-27 13:47 UTC by ErezBiren

Add ranking stars badges (Only for GitHub repositories)

solve #113

2023-02-27 13:55 UTC, UrielOfir commented
Hi Erez, thank you for your contribution :)
Please fix the conflict. In your PR you don't have the main language badge, please update it from the current main branch.

2023-02-27 13:59 UTC, UrielOfir commented
resolves #113

2023-02-27 14:04 UTC, UrielOfir requested changes

2023-02-27 14:04 UTC, UrielOfir commented on README.md
> +![GitHub stars](https://img.shields.io/github/stars/lirantal/typeform-client?style=flat-square)
main language badge is missing.

2023-02-27 14:17 UTC, ErezBiren commented on README.md
> +![GitHub stars](https://img.shields.io/github/stars/lirantal/typeform-client?style=flat-square)
Thanks! 
Added

2023-02-27 14:23 UTC, ErezBiren commented
> Hi Erez, thank you for your contribution :) Please fix the conflict. In your PR you don't have the main language badge, please update it from the current main branch.

Thanks! hope I fixed it right this time

2023-02-28 05:53 UTC, UrielOfir approved these changes
Thank you for your contribution :)

2023-02-28 05:53 UTC, merged